# Generated by Django 5.0.3 on 2024-03-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_blogcomment_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
