# Generated by Django 5.0.1 on 2024-04-04 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_comment_blogcomment_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
